### ISSUE TITLE
Rubber ducky

### ISSUE THREAD

**Issue by ibrahimamir84** [UndedInside/DuckyScripts#3]

**Comment by UndedInside** [comment]
Yep, this is for a rubber ducky or any device that runs DuckyScript.

If there is a problem with any of the payloads please specify which payload and tell me the error

**Comment by UndedInside** [comment]
Yep, this is for a rubber ducky or any device that runs DuckyScript.

If there is a problem with any of the payloads please specify which payload and tell me the error
